version: '3.9'
services:
  mlflow_postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - mlflow_postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=mlflow_database
      - POSTGRESQL_USERNAME=mlflow_user
      - POSTGRESQL_PASSWORD=mlflow_pw
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - apps-of-app-net
  mlflow_server:
    restart: always
    build: ./
    image: docker-lab/mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=adminSecretKey123
    command: mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_pw@mlflow_postgresql:5432/mlflow_database --default-artifact-root s3://mlflow/ --host 0.0.0.0
    networks:
      - apps-of-app-net
volumes:
  mlflow_postgresql_data:
networks:
  apps-of-app-net:
    name: apps-of-app-net