version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2022-10-15T19-57-03Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminSecretKey123
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - apps-of-app-net
volumes:
  minio_data:
networks:
  apps-of-app-net:
    name: apps-of-app-net